name: Build & Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: {node-version:18}
      - run: npm ci
      - name: Create .env.local
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env.local
          echo "ASSISTANT_ID=${{ secrets.ASSISTANT_ID }}" >> .env.local
          echo "FIREBASE_SERVICE_ACCOUNT_KEY=${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}" >> .env.local
          echo "ADMIN_API_KEY=${{ secrets.ADMIN_API_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> .env.local
          # osv.
      - run: npm run lint && npm test && npm run build
      - run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}